config/routes.rb
Rails.application.routes.draw do
  get 'charts/downloads_by_day'
  devise_for :users
  root 'dashboard#index'

  resources :meals
  resources :products
  resources :activities

  resource :profile
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  validates :duration, numericality: { greater_than: 0 }
  validates :completed_on, presence: true
  validates :activity_type, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

end

app/models/meal.rb
class Meal < ApplicationRecord
  before_save :set_calories_from_product

  belongs_to :user
  belongs_to :product

  validates :meal_type, inclusion: { in: ["breakfast", "lunch", "dinner", "supper", "snacks"]}
  validates :quantity, numericality: { greater_than: 0 }

  def set_calories_from_product
    self.calories = product.calories_per_100 * quantity / 100
  end

  def name
    product.name
  end

  def category
    product.category.name
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :meals
  belongs_to :category
  belongs_to :user, optional: true
  validates :name, presence: true
  validates :calories_per_100, numericality: { greater_than: 0 }

  def self.for_user(user)
    self.where(user_id: user.id) + self.where(user_id: nil)
  end

  def select_title
    "#{name} (#{calories_per_100} kcal)"
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  enum gender: [:male, :female]

  belongs_to :user

  validates :gender, presence: true
  validates :date_of_birth, presence: true
  validates :weight, numericality: { greater_than: 0 }
  validates :height, numericality: { greater_than: 0 }
  validates :activity_level, inclusion: { in: (0..5) }

  def body_mass_index
    ((weight / height**2 * 100)*100).round(2)
  end

  def basal_metabolic_rate
    if gender == 'male'
      (66.5 + (13.75 * weight) + (5.003 * height) - (6.775 * age)).round
    else
      (665.1 + (9.563 * weight) + (1.85 * height) - (4.676 * age)).round
    end
  end

  def age
    ((Date.today - date_of_birth) / 365).to_i
  end

  def activity_factor
    case activity_level
    when 0 then 1.25
    when 1 then 1.4
    when 2 then 1.6
    when 3 then 1.75
    when 4 then 2.0
    when 5 then 2.3
    end
  end

  def total_metabolic_rate
    (basal_metabolic_rate * activity_factor).round
  end

  def today_balance
    user.meals.where(eaten_on: Date.today).sum(:calories) - total_metabolic_rate
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :meals
  has_many :activities
  has_many :products

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    before_action :authenticate_user!

  def index
    @activities = current_user.activities
  end

  def new
    @activity = current_user.activities.build
  end

  def create
    @activity = current_user.activities.build(activity_params)
    if @activity.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def show
    @activity = current_user.activities.find(params[:id])
  end

  def edit
    @activity = current_user.activities.find(params[:id])

  end

  def update
    @activity = current_user.activities.find(params[:id])
    @activity.update(activity_params)
    if @activity.save
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  def destroy
    @activity = current_user.activities.find(params[:id])
    @activity.destroy
    redirect_to action: 'index'
  end

  private

  def activity_params
    params.require(:activity).permit(:duration, :completed_on, :activity_type)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def downloads_by_day
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @profile = current_user.profile

    if @profile
      render :index
    else
      render :index_no_profile
    end
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_empty_product, only: [:new, :create, :edit, :update]

  def index
    @meals = current_user.meals

    if params[:meal_type].present?
      @meals = @meals.where(meal_type: params[:meal_type])
    end

    if params[:eaten_on].present?
      @meals = @meals.where(eaten_on: params[:eaten_on])
    end
  end

  def show
    @meal = current_user.meals.find(params[:id])
  end

  def new
    @meal = current_user.meals.build
    @meal.meal_type = params[:meal_type]
    @meal.eaten_on = params[:eaten_on]
  end

  def create
    @meal = current_user.meals.build(meal_params)
    if @meal.save
      redirect_to action: 'index', eaten_on: @meal.eaten_on
    else
      render :new
    end
  end

  def edit
    @meal = current_user.meals.find(params[:id])
  end

  def destroy
    @meal =  current_user.meals.find(params[:id])
    @meal.destroy
    redirect_to action: 'index', eaten_on: @meal.eaten_on
  end

  def update
    @meal =  current_user.meals.find(params[:id])
    if @meal.update(meal_params)
      redirect_to action: 'index', eaten_on: @meal.eaten_on
    else
      render :edit
    end
  end

  private

  def set_empty_product
    @product = current_user.products.build
  end

  def meal_params
    params.require(:meal).permit(:name, :quantity, :calories, :category, :eaten_on, :meal_type, :product_id)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def create
    @product = current_user.products.new(product_params)
    @product.save
  end

  private

  def product_params
    params.require(:product).permit(:name, :category_id, :calories_per_100)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def new
    @profile = current_user.build_profile
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    @profile.update(profile_params)
    render :edit
  end

  private

  def profile_params
    params.require(:profile).permit(:gender, :date_of_birth, :weight, :height, :activity_level, :purpose)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/dashboard/_footer.html.haml
.container-fluid.p-3.p-md-5.footer
  Copyright &copy;
  = Date.today.year
  by Sylwia Miecznikowska
  |
  = link_to 'Github', 'http://github.com/sylwiaa/calories-counter'

app/views/dashboard/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light
  %navbar-brand.logo= link_to 'CaloriesCounter', root_path
  %button.navbar-toggler{"aria-controls" => "navbarNavAltMarkup", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavAltMarkup", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNavAltMarkup.collapse.navbar-collapse
    %ul.navbar-nav.ml-auto
      - if user_signed_in?
        %li.nav-item
          = link_to edit_user_registration_path, class: 'nav-link' do
            %i.fa.fa-user-o
            Edit account
        %li.nav-item
          = link_to destroy_user_session_path, method: :delete, class: 'nav-link' do
            %i.fa.fa-sign-out
            Log out
      - else
        %li.nav-item
          = link_to new_user_session_path, class: 'nav-link' do
            %i.fa.fa-user-o
            Log in
        %li.nav-item
          = link_to new_user_registration_path, class: 'nav-link' do
            %i.fa.fa-sign-out
            Registration

app/views/dashboard/index.html.haml
.container.dashboard-header
  .row
    .col-sm-6
      %h2 Today
      %h2= Date.today
    .col-sm-6
      %table.table.table-sm.table-bordered
        %thead
          %tr
            %th BMI
            %th Basal metabolic rate
            %th Total metabolic rate
        %tbody
          %tr
            %td= current_user.profile.body_mass_index
            %td
              =current_user.profile.basal_metabolic_rate
              %span kcal
            %td
              =current_user.profile.total_metabolic_rate
              %span kcal

    = line_chart current_user.meals.group(:eaten_on).sum(:calories)
.container.dashboard-list
  - today = Date.today
  - (0...7).each do |day|
    .dashboard-list-item
      - current_day = today - day

      %h1.day-header= current_day

      - calories_by_meal_type = current_user.meals.group(:meal_type).where(eaten_on: current_day).sum(:calories)
      .calories
        %h4
          The amount of calories during the day:
          = current_user.meals.where(eaten_on: current_day).sum(:calories)
          %span kcal
          = link_to "[view list]", meals_path(eaten_on: current_day)
      .row
        .col-sm.links
          = link_to new_meal_path(meal_type: "breakfast", eaten_on: current_day) do
            = image_tag 'breakfast.png', width: 90
          .name_category
            = link_to 'Breakfast [+]', new_meal_path(meal_type: "breakfast", eaten_on: current_day)
            %br
            = calories_by_meal_type["breakfast"] || 0
            %span kcal

        .col-sm.links
          = link_to new_meal_path(meal_type: "lunch", eaten_on: current_day) do
            = image_tag 'lunch.png', width: 90
          .name_category
            = link_to 'Lunch [+]', new_meal_path(meal_type: "lunch", eaten_on: current_day)
            %br
            = calories_by_meal_type["lunch"] || 0
            %span kcal

        .col-sm.links
          = link_to new_meal_path(meal_type: "dinner", eaten_on: current_day) do
            = image_tag 'dinner.png', width: 90
          .name_category
            = link_to 'Dinner [+]', new_meal_path(meal_type: "dinner", eaten_on: current_day)
            %br
            = calories_by_meal_type["dinner"] || 0
            %span kcal

        .col-sm.links
          = link_to new_meal_path(meal_type: "supper", eaten_on: current_day) do
            = image_tag 'supper.png', width: 90
          .name_category
            = link_to 'Supper [+]', new_meal_path(meal_type: "supper", eaten_on: current_day)
            %br
            = calories_by_meal_type["supper"] || 0
            %span kcal

        .col-sm.links
          = link_to new_meal_path(meal_type: "snacks", eaten_on: current_day) do
            = image_tag 'snacks.png', width: 90
          .name_category
            = link_to 'Snacks [+]', new_meal_path(meal_type: "snacks", eaten_on: current_day)
            %br
            = calories_by_meal_type["snacks"] || 0
            %span kcal

        .col-sm.links
          = link_to new_activity_path do
            = image_tag 'activity.png', width: 90
          .name_category
            = link_to 'Activity [+]', new_activity_path
            %br
            = current_user.activities.sum(:duration)
            %span minutes

app/views/dashboard/index_no_profile.html.haml
.container.dashboard_no_profile
  .row
    .col-sm-4
      %i.fa.fa-check-square-o
      %h3 Sign up
    .col-sm-4
      %i.fa.fa-square-o
      %h3= link_to 'Set up profile', new_profile_path
    .col-sm-4
      %i.fa.fa-square-o
      %h3 Add meal history