config/routes.rb
Rails.application.routes.draw do
  get 'charts/downloads_by_day'
  devise_for :users
  root 'dashboard#index'

  resources :meals
  resources :products
  resources :activities

  resource :profile
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  validates :duration, numericality: { greater_than: 0 }
  validates :completed_on, presence: true
  validates :activity_type, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

end

app/models/meal.rb
class Meal < ApplicationRecord
  before_save :set_calories_from_product

  belongs_to :user
  belongs_to :product

  validates :meal_type, inclusion: { in: ["breakfast", "lunch", "dinner", "supper", "snacks"]}
  validates :quantity, numericality: { greater_than: 0 }

  def set_calories_from_product
    self.calories = product.calories_per_100 * quantity / 100
  end

  def name
    product.name
  end

  def category
    product.category.name
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :meals
  belongs_to :category
  belongs_to :user, optional: true
  validates :name, presence: true
  validates :calories_per_100, numericality: { greater_than: 0 }

  def self.for_user(user)
    self.where(user_id: user.id) + self.where(user_id: nil)
  end

  def select_title
    "#{name} (#{calories_per_100} kcal)"
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  enum gender: [:male, :female]

  belongs_to :user

  validates :gender, presence: true
  validates :date_of_birth, presence: true
  validates :weight, numericality: { greater_than: 0 }
  validates :height, numericality: { greater_than: 0 }
  validates :activity_level, inclusion: { in: (0..5) }

  def body_mass_index
    ((weight / height**2 * 100)*100).round(2)
  end

  def basal_metabolic_rate
    if gender == 'male'
      (66.5 + (13.75 * weight) + (5.003 * height) - (6.775 * age)).round
    else
      (665.1 + (9.563 * weight) + (1.85 * height) - (4.676 * age)).round
    end
  end

  def age
    ((Date.today - date_of_birth) / 365).to_i
  end

  def activity_factor
    case activity_level
    when 0 then 1.25
    when 1 then 1.4
    when 2 then 1.6
    when 3 then 1.75
    when 4 then 2.0
    when 5 then 2.3
    end
  end

  def total_metabolic_rate
    (basal_metabolic_rate * activity_factor).round
  end

  def today_balance
    user.meals.where(eaten_on: Date.today).sum(:calories) - total_metabolic_rate
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :meals
  has_many :activities
  has_many :products

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    before_action :authenticate_user!

  def index
    @activities = current_user.activities
  end

  def new
    @activity = current_user.activities.build
  end

  def create
    @activity = current_user.activities.build(activity_params)
    if @activity.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def show
    @activity = current_user.activities.find(params[:id])
  end

  def edit
    @activity = current_user.activities.find(params[:id])

  end

  def update
    @activity = current_user.activities.find(params[:id])
    @activity.update(activity_params)
    if @activity.save
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  def destroy
    @activity = current_user.activities.find(params[:id])
    @activity.destroy
    redirect_to action: 'index'
  end

  private

  def activity_params
    params.require(:activity).permit(:duration, :completed_on, :activity_type)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def downloads_by_day
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @profile = current_user.profile

    if @profile
      render :index
    else
      render :index_no_profile
    end
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_empty_product, only: [:new, :create, :edit, :update]

  def index
    @meals = current_user.meals

    if params[:meal_type].present?
      @meals = @meals.where(meal_type: params[:meal_type])
    end

    if params[:eaten_on].present?
      @meals = @meals.where(eaten_on: params[:eaten_on])
    end
  end

  def show
    @meal = current_user.meals.find(params[:id])
  end

  def new
    @meal = current_user.meals.build
    @meal.meal_type = params[:meal_type]
    @meal.eaten_on = params[:eaten_on]
  end

  def create
    @meal = current_user.meals.build(meal_params)
    if @meal.save
      redirect_to action: 'index', eaten_on: @meal.eaten_on
    else
      render :new
    end
  end

  def edit
    @meal = current_user.meals.find(params[:id])
  end

  def destroy
    @meal =  current_user.meals.find(params[:id])
    @meal.destroy
    redirect_to action: 'index', eaten_on: @meal.eaten_on
  end

  def update
    @meal =  current_user.meals.find(params[:id])
    if @meal.update(meal_params)
      redirect_to action: 'index', eaten_on: @meal.eaten_on
    else
      render :edit
    end
  end

  private

  def set_empty_product
    @product = current_user.products.build
  end

  def meal_params
    params.require(:meal).permit(:name, :quantity, :calories, :category, :eaten_on, :meal_type, :product_id)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def create
    @product = current_user.products.new(product_params)
    @product.save
  end

  private

  def product_params
    params.require(:product).permit(:name, :category_id, :calories_per_100)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def new
    @profile = current_user.build_profile
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    @profile.update(profile_params)
    render :edit
  end

  private

  def profile_params
    params.require(:profile).permit(:gender, :date_of_birth, :weight, :height, :activity_level, :purpose)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/activities/_form.html.haml
- if @activity.errors.present?
  .alert.alert-danger.alert-dismissible.fade.show{:role => "alert"}
    %ul
      - @activity.errors.full_messages.each do |message|
        %li
          %strong= message
        %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
          %span{"aria-hidden" => "true"}

= form_for @activity, html: { multipart: true } do |f|
  %h5 Duration*
  = f.number_field :duration, class: 'form-control'
  %sup * in minutes

  %h5 Activity type
  = f.text_field :activity_type, class: 'form-control'

  %h5 Completed on
  = f.date_select :completed_on, class: 'form-control'

  %br
  = f.submit "Wyślij", class: 'btn btn-default'

app/views/activities/edit.html.haml
.container
  = link_to 'Cofnij', activities_path
  %h2 Edit activity
  .row
    .col-sm-6
      = render partial: 'form', activity: @activity

app/views/activities/index.html.haml
.container.activity-index
  .back= link_to 'Back', root_path
  %h3 Activities:
  %span= link_to 'Add more activities', new_activity_path
  %table.table.table-sm
    %thead
      %tr
        %th{:scope => "col"} #
        %th{:scope => "col"} Activity type
        %th{:scope => "col"} Duration
        %th{:scope => "col"} Completed on
        %th{:scope => "col"} Delete
    %tbody
      - @activities.each_with_index do |activity, index|
        %tr
          %td{:scope => "row"}= index + 1
          %td= link_to activity.activity_type, activity_path(activity)
          %td= activity.duration
          %td= activity.completed_on
          %td= link_to "X", activity_path(activity), method: :delete, data: {confirm: 'Jesteś pewnien?'}

app/views/activities/new.html.haml
.container
  .back= link_to 'Back', root_path
  %h2 Add activity
  %span= Date.today
  .row
    .col-sm-6
      = render partial: 'form', activity: @activity

app/views/activities/show.html.haml
.container.show-activity
  .back= link_to 'Cofnij', activities_path
  %h1 Activity
  = link_to 'Edit activity', edit_activity_path(@activity)
  = link_to "Delete", activity_path(@activity), method: :delete, data: {confirm: 'Are you sure?'}, class: 'delete'
  %table.table.table-bordered
    %thead
      %tr
        %th{:scope => "col"} Duration
        %th{:scope => "col"} Completed on
        %th{:scope => "col"} Activity type
    %tbody
      %tr
        %th= @activity.duration
        %th= @activity.completed_on
        %th= @activity.activity_type

app/views/charts/downloads_by_day.html.haml
%h1 Charts#downloads_by_day
= line_chart Download.group_by_day(:created_at).count
    

app/views/meals/_form.html.haml
= render 'products/form'

- if @meal.errors.present?
  .alert.alert-danger.alert-dismissible.fade.show{:role => "alert"}
    %ul
      - @meal.errors.full_messages.each do |message|
        %li
          %strong= message
        %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
          %span{"aria-hidden" => "true"}


= form_for @meal, html: { multipart: true } do |f|
  %h5 Add or select product:
  %a.btn.btn-primary{ "data-toggle" => "modal", "data-target" => "#productModal" } Add Product
  %br
  = f.collection_select :product_id, Product.for_user(current_user), :id, :select_title, {prompt: true},  class: 'form-control'

  %h5 Meal type:
  = f.text_field :meal_type, class: 'form-control'

  %h5 Quantity:
  = f.number_field :quantity, class: 'form-control'

  %h5 Eaten on:
  = f.date_select :eaten_on, class: 'form-control'
  %br
  = f.submit "Wyślij", class: 'btn btn-default'

app/views/meals/edit.html.haml
.container.meal
  .back= link_to 'Cofnij', meals_path
  .row
    .col-sm-12
      %h3 Edit meal
      = render partial: 'form', meal: @meal

app/views/meals/index.html.haml
.container.index-meal
  .row
    .col-sm-12
      %h3 List of meals eaten on:
      %span= params[:eaten_on]
    .col-xs-12
      %table.table.table-striped
        %tr.success
          %th{:scope => "col"} Name:
          %th{:scope => "col"} Meal type:
          %th{:scope => "col"} Calories:
        - @meals.each do |meal|
          %tr
            %td= link_to meal.name, meal_path(meal)
            %td= meal.meal_type
            %td= meal.calories

app/views/meals/new.html.haml
.container.meal
  .back= link_to 'Back', meals_path
  - if params[:meal_type]
    %div
      %i.fa.fa-cutlery
      %span= params[:meal_type].capitalize
  .row
    .col-sm-12
      = render partial: 'form', meal: @meal

app/views/meals/show.html.haml
.container.show-meal
  .back= link_to 'Cofnij', root_path
  %h1 Meal

  = link_to 'Edit meal', edit_meal_path(@meal)
  = link_to "Delete", meal_path(@meal), method: :delete, data: {confirm: 'Are you sure?'}, class: 'delete'

  %table.table.table-striped
    %tr.success
      %th Name:
      %th Quantity:
      %th Meal type:
      %th Calories:
      %th Category:
      %th Eaten on:
    %tr
      %td= @meal.name
      %td= @meal.quantity
      %td= @meal.meal_type
      %td= @meal.calories
      %td= @meal.category
      %td= @meal.eaten_on

app/views/products/_form.html.haml
= form_for @product, remote: true do |f|
  .modal#productModal
    .modal-dialog
      .modal-content
        .modal-header
          .modal-title Create product
        .modal-body
          %h5 Name
          = f.text_field :name, class: 'form-control'

          %h5 Category
          = f.collection_select :category_id, Category.order(:name), :id, :name, {prompt: true}, class: 'form-control'

          %h5 Calories per 100g
          = f.number_field :calories_per_100, class: 'form-control'

        .modal-footer
          %button.btn.btn-secondary{ "data-dismiss" => "modal" } Close
          = f.submit class: 'btn btn-primary'

app/views/products/create.js.erb
<% if @product.errors.present? %>
  alert('<%= @product.errors.full_messages.first %>')
<% else %>
  window.location.reload()
<% end %>

app/views/profiles/_form.html.haml
- if @profile.errors.present?
  .alert.alert-danger.alert-dismissible.fade.show{:role => "alert"}
    %ul
      - @profile.errors.full_messages.each do |message|
        %li
          %strong= message
        %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
          %span{"aria-hidden" => "true"}


= form_for @profile, url: profile_path, html: { multipart: true } do |f|
  .row
    .col-md-6.mb-3
      = f.radio_button :gender, 'male'
      = label :gender_male, 'male'
      = f.radio_button :gender, 'female'
      = label :gender_female, 'female'
  .row
    .col-md-3.mb-3
      = f.label :weight
      = f.number_field :weight, class: 'form-control'
    .col-md-3.mb-3
      = f.label :height
      = f.number_field :height, class: 'form-control'
  .row
    .col-md-6.mb-3
      = f.label :date_of_birth
      %br
      = f.date_select :date_of_birth, start_year: 1980, end_year: 2010, order: [:month, :day, :year], class: 'custom-select'
  .row
    .col-md-6.mb-3
      = f.label :activity_level
      %br
      = f.select :activity_level, [["patient lying in bed", 0], ["low physical activity", 1], ["moderate physical activity", 2], ["active lifestyle", 3], ["very active lifestyle", 4], ["competitive sport", 5] ], {include_blank: true}, class: 'form-control'
  .row
    .col-md-6.mb-3
      = f.label :purpose
      %br
      = f.select :purpose, [["lose weight", 0], ["gain weight", 1], ["maintain weight", 2]], { include_blank: true }, class: 'form-control'
  = f.submit "Wyślij", class: 'btn btn-default'

app/views/profiles/edit.html.haml
.container
  .back= link_to 'Back', root_path
  %h3 Profile #{current_user.email}

  %ul.nav.nav-tabs
    %li.nav-item
      = link_to 'Edit account', edit_user_registration_path, class: 'nav-link'
    %li.nav-item
      %a.nav-link.active{:href => "#"} Edit profile

  .row
    .col-sm-12
      = render partial: 'form', profile: @profile

app/views/profiles/new.html.haml
.container
  .back= link_to 'Cofnij', root_path
  .row
    .col-sm-12
      %h3 Create profile
      = render partial: 'form', profile: @profile